export const genres = [
  { backgroundImage: "80.PNG", name: "80" },
  { backgroundImage: "90.PNG", name: "90" },
  { backgroundImage: "noImage.PNG", name: "Alternative" },
  { backgroundImage: "noImage.PNG", name: "Anime" },
  { backgroundImage: "blues.PNG", name: "Blues" },
  { backgroundImage: "noImage.PNG", name: "Children’s Music" },
  { backgroundImage: "classical.PNG", name: "Classical" },
  { backgroundImage: "noImage.PNG", name: "Comedy" },
  { backgroundImage: "noImage.PNG", name: "Commercial" },
  { backgroundImage: "country.PNG", name: "Country" },
  { backgroundImage: "noImage.PNG", name: "Dance" },
  { backgroundImage: "noImage.PNG", name: "Disney" },
  { backgroundImage: "noImage.PNG", name: "Easy Listening" },
  { backgroundImage: "electronic.PNG", name: "Electronic" },
  { backgroundImage: "folk.PNG", name: "Folk music" },
  { backgroundImage: "noImage.PNG", name: "Fitness & Workout" },
  { backgroundImage: "noImage.PNG", name: "Hip-Hop" },
  { backgroundImage: "noImage.PNG", name: "Holiday" },
  { backgroundImage: "noImage.PNG", name: "Indie Pop" },
  { backgroundImage: "noImage.PNG", name: "Industrial" },
  { backgroundImage: "noImage.PNG", name: "Inspirational" },
  { backgroundImage: "noImage.PNG", name: "Instrumental" },
  { backgroundImage: "noImage.PNG", name: "J-Pop" },
  { backgroundImage: "jazz.PNG", name: "Jazz" },
  { backgroundImage: "noImage.PNG", name: "K-Pop" },
  { backgroundImage: "noImage.PNG", name: "Karaoke" },
  { backgroundImage: "noImage.PNG", name: "Kayokyoku" },
  { backgroundImage: "latin.PNG", name: "Latin" },
  { backgroundImage: "noImage.PNG", name: "New Age" },
  { backgroundImage: "noImage.PNG", name: "Opera" },
  { backgroundImage: "oldies.PNG", name: "Oldies" },
  { backgroundImage: "pop.PNG", name: "Pop" },
  { backgroundImage: "r&b.PNG", name: "R&B" },
  { backgroundImage: "raggae.PNG", name: "Reggae" },
  { backgroundImage: "rap.PNG", name: "Rap" },
  { backgroundImage: "rock.PNG", name: "Rock" },
  { backgroundImage: "noImage.PNG", name: "Singer" },
  { backgroundImage: "noImage.PNG", name: "Soundtrack" },
  { backgroundImage: "noImage.PNG", name: "Spoken Word" },
  { backgroundImage: "noImage.PNG", name: "Tex-Mex " },
  { backgroundImage: "noImage.PNG", name: "Vocal" },
  { backgroundImage: "noImage.PNG", name: "World" }
];

export default { genres };